# Generated by Django 5.2.5 on 2025-10-10 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0004_aiplan_alter_aiquestion_importance_aierrorlog_and_more"),
        ("appointments", "0004_slot_price"),
        ("payments", "0003_alter_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                help_text="در صورت پرداخت برای اشتراک، این فیلد پر می\u200cشود.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="ai_assistant.subscription",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                help_text="در صورت پرداخت برای قرار ملاقات، این فیلد پر می\u200cشود.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="appointments.appointment",
            ),
        ),
    ]
