# Generated by Django 5.2.5 on 2025-10-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="passwordresetcode",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="passwordresetcode",
            name="attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="passwordresetcode",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("signup", "Signup"),
                    ("reset", "Password Reset"),
                    ("phone_verify", "Phone Verification"),
                ],
                default="test",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="passwordresetcode",
            index=models.Index(
                fields=["phone_number", "purpose"],
                name="users_passw_phone_n_7855f8_idx",
            ),
        ),
    ]
