# Generated by Django 5.2.5 on 2025-09-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientprofile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/clients/"
            ),
        ),
        migrations.AddField(
            model_name="lawyerprofile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/lawyers/"
            ),
        ),
    ]
