# Generated by Django 5.2.5 on 2025-10-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_clientprofile_avatar_lawyerprofile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="lawyerprofile",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="lawyerprofile",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="lawyerprofile",
            name="specialization",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
