# Generated by Django 5.2.5 on 2025-10-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_lawyerprofile_bio_lawyerprofile_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="device_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
