# Generated by Django 4.2.30 on 2026-06-08 11:53

import apps.bookings.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lawyers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "booking_type",
                    models.CharField(
                        choices=[
                            ("consultation", "Initial Consultation"),
                            ("followup", "Follow-up Session"),
                            ("document_review", "Document Review"),
                            ("representation", "Legal Representation"),
                        ],
                        default="consultation",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                ("duration_minutes", models.PositiveIntegerField(default=30)),
                ("subject", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                ("practice_area", models.CharField(blank=True, max_length=50)),
                ("lawyer_notes", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("meeting_link", models.URLField(blank=True)),
                ("meeting_location", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        limit_choices_to={"role": "customer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lawyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="lawyers.lawyerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "bookings",
                "ordering": ["-scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="BookingDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("id", "Government ID"),
                            ("contract", "Contract"),
                            ("evidence", "Evidence"),
                            ("court_filing", "Court Filing"),
                            ("financial", "Financial Record"),
                            ("medical", "Medical Record"),
                            ("property", "Property Document"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.bookings.models.booking_document_path
                    ),
                ),
                ("file_size", models.PositiveIntegerField(default=0)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("is_confidential", models.BooleanField(default=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="bookings.booking",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "booking_documents",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
