# Generated by Django 4.2.30 on 2026-06-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="duration_minutes",
            field=models.PositiveIntegerField(default=60),
        ),
    ]
