# Generated by Django 4.2.30 on 2026-06-10 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookings", "0002_alter_booking_duration_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="cancellation_fee",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="booking",
            name="cancellation_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancelled_bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="refund_amount",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="booking",
            name="refund_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="refund_status",
            field=models.CharField(
                choices=[
                    ("none", "بدون بازگشت وجه"),
                    ("requested", "درخواست بازگشت وجه"),
                    ("not_eligible", "غیرقابل بازگشت"),
                    ("approved", "تایید شده"),
                    ("paid", "پرداخت شده"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="BookingCancellationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                (
                    "hours_before_session",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "refund_amount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                (
                    "cancellation_fee",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                ("refund_status", models.CharField(default="none", max_length=20)),
                ("admin_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancellation_logs",
                        to="bookings.booking",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "booking_cancellation_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
