# Generated by Django 5.2.5 on 2025-10-17 17:12

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("searchs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="searchhistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="search_history",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="searchhistory",
            index=models.Index(
                fields=["user", "created_at"], name="searchs_sea_user_id_ddfa42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchhistory",
            index=models.Index(
                fields=["normalized_query"], name="searchs_sea_normali_0d1095_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchhistory",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["normalized_query"],
                name="sh_norm_query_gin",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="searchhistory",
            unique_together={("user", "normalized_query")},
        ),
    ]
