# Generated by Django 5.2.5 on 2025-10-06 17:25

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("searchs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="searchhistory",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="searchhistory",
            name="normalized_query",
            field=models.CharField(default="", editable=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="searchhistory",
            unique_together={("user", "normalized_query")},
        ),
        migrations.AddIndex(
            model_name="searchhistory",
            index=models.Index(
                fields=["user", "created_at"], name="searchs_sea_user_id_ddfa42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchhistory",
            index=models.Index(
                fields=["normalized_query"], name="searchs_sea_normali_0d1095_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchhistory",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["normalized_query"],
                name="sh_norm_query_gin",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
