# Generated by Django 5.2.5 on 2025-10-17 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
        ("lawyer_profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="lawyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cases",
                to="lawyer_profile.lawyerprofile",
            ),
        ),
        migrations.AddField(
            model_name="casecomment",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="cases.case",
            ),
        ),
        migrations.AddField(
            model_name="casecomment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="cases.casecomment",
            ),
        ),
    ]
