# Generated by Django 5.2.5 on 2025-10-07 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0004_lawyerprofile_bio_lawyerprofile_city_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LawyerClientRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lawyer_relations",
                        to="users.clientprofile",
                    ),
                ),
                (
                    "lawyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_relations",
                        to="users.lawyerprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("lawyer", "client")},
            },
        ),
    ]
