# Generated by Django 5.2.5 on 2025-10-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lawyerclientrelation",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="lawyerclientrelation",
            name="last_interaction",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lawyerclientrelation",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lawyerclientrelation",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
