# Generated by Django 5.2.5 on 2025-10-17 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
        ("lawyer_profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lawyerclientrelation",
            name="lawyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_relations",
                to="lawyer_profile.lawyerprofile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lawyerclientrelation",
            unique_together={("lawyer", "client")},
        ),
    ]
