# Generated by Django 4.2.30 on 2026-06-08 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LawyerProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bar_number", models.CharField(max_length=50, unique=True)),
                (
                    "headline",
                    models.CharField(
                        blank=True,
                        help_text="E.g. 'Senior Partner at Smith & Associates'",
                        max_length=200,
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                ("years_experience", models.PositiveIntegerField(default=0)),
                (
                    "hourly_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "consultation_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Fee for initial 30-min consultation",
                        max_digits=10,
                    ),
                ),
                ("languages", models.JSONField(blank=True, default=list)),
                ("office_address", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("linkedin", models.URLField(blank=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("is_accepting_clients", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("total_reviews", models.PositiveIntegerField(default=0)),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("total_bookings", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "lawyer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lawyer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "lawyer_profiles",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField()),
                ("comment", models.TextField(blank=True)),
                ("is_anonymous", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="given_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lawyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="lawyers.lawyerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "lawyer_reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institution", models.CharField(max_length=200)),
                ("degree", models.CharField(max_length=200)),
                ("year_graduated", models.PositiveIntegerField()),
                (
                    "lawyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education",
                        to="lawyers.lawyerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "lawyer_education",
                "ordering": ["-year_graduated"],
            },
        ),
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("mon", "Monday"),
                            ("tue", "Tuesday"),
                            ("wed", "Wednesday"),
                            ("thu", "Thursday"),
                            ("fri", "Friday"),
                            ("sat", "Saturday"),
                            ("sun", "Sunday"),
                        ],
                        max_length=3,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("slot_duration_minutes", models.PositiveIntegerField(default=30)),
                (
                    "lawyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability",
                        to="lawyers.lawyerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "lawyer_availability",
                "ordering": ["day_of_week", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="PracticeArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("corporate", "Corporate Law"),
                            ("criminal", "Criminal Defense"),
                            ("family", "Family Law"),
                            ("immigration", "Immigration"),
                            ("intellectual_property", "Intellectual Property"),
                            ("real_estate", "Real Estate"),
                            ("employment", "Employment Law"),
                            ("tax", "Tax Law"),
                            ("personal_injury", "Personal Injury"),
                            ("bankruptcy", "Bankruptcy"),
                            ("civil_litigation", "Civil Litigation"),
                            ("estate_planning", "Estate Planning"),
                            ("healthcare", "Healthcare Law"),
                            ("environmental", "Environmental Law"),
                            ("international", "International Law"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "lawyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_areas",
                        to="lawyers.lawyerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "lawyer_practice_areas",
                "unique_together": {("lawyer", "area")},
            },
        ),
    ]
