# Generated by Django 4.2.30 on 2026-06-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lawyers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lawyerprofile",
            name="bar_document",
            field=models.FileField(blank=True, null=True, upload_to="lawyer_licenses/"),
        ),
    ]
