# Generated by Django 4.2.30 on 2026-06-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lawyers", "0002_lawyerprofile_bar_document"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="availability",
            options={"ordering": ["date", "day_of_week", "start_time"]},
        ),
        migrations.AddField(
            model_name="availability",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="availability",
            name="is_closed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="availability",
            name="day_of_week",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mon", "Monday"),
                    ("tue", "Tuesday"),
                    ("wed", "Wednesday"),
                    ("thu", "Thursday"),
                    ("fri", "Friday"),
                    ("sat", "Saturday"),
                    ("sun", "Sunday"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
