# Generated by Django 4.2.30 on 2026-06-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lawyers", "0003_alter_availability_options_availability_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lawyerprofile",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
