# Generated by Django 4.2.30 on 2026-06-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lawyers", "0004_lawyerprofile_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="availability",
            name="slot_duration_minutes",
            field=models.PositiveIntegerField(default=60),
        ),
    ]
