# Generated by Django 5.2.5 on 2025-10-07 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0002_lawyerclientrelation_is_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LawyerReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField()),
                ("comment", models.TextField(blank=True, null=True)),
                ("is_approved", models.BooleanField(default=True)),
                ("reply", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="common.lawyerclientrelation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("relation", "created_at")},
            },
        ),
    ]
