# Generated by Django 5.2.5 on 2025-10-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_lawyerclientrelation_is_active_and_more"),
        ("rating_and_reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="lawyerreview",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="lawyerreview",
            name="comment",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lawyerreview",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="lawyerreview",
            name="reply",
            field=models.TextField(blank=True, default="online"),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="lawyerreview",
            constraint=models.UniqueConstraint(
                fields=("relation",), name="unique_review_per_relation"
            ),
        ),
    ]
