# Generated by Django 5.2.5 on 2025-10-07 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="client",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="lawyer",
        ),
        migrations.RemoveField(
            model_name="message",
            name="conversation",
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["created_at"]},
        ),
        migrations.RenameField(
            model_name="message",
            old_name="text",
            new_name="content",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="timestamp",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
