# Generated by Django 5.2.5 on 2025-10-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LawyerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expertise", models.CharField(blank=True, max_length=200)),
                ("degree", models.CharField(blank=True, max_length=200)),
                ("experience_years", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("busy", "Busy"),
                        ],
                        default="offline",
                        max_length=10,
                    ),
                ),
                (
                    "document",
                    models.FileField(blank=True, null=True, upload_to="lawyer_docs/"),
                ),
                ("bio", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("specialization", models.CharField(blank=True, max_length=100)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="lawyer_avatars/"
                    ),
                ),
                (
                    "office_address",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
