# Generated by Django 5.2.5 on 2025-10-19 18:04

import lawyer_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lawyer_profile", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lawyerprofile",
            name="document",
        ),
        migrations.AddField(
            model_name="lawyerprofile",
            name="license_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="lawyerprofile",
            name="office_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="lawyerprofile",
            name="office_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="lawyerprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=lawyer_profile.models.avatar_upload_path,
            ),
        ),
    ]
