# Generated by Django 5.2.5 on 2025-10-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lawyer_profile", "0003_remove_lawyerprofile_document_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lawyerprofile",
            name="region",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
