# Generated by Django 5.2.5 on 2025-10-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIErrorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(blank=True, null=True)),
                ("error", models.TextField()),
                ("traceback", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AIPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("daily_limit", models.PositiveIntegerField(default=10)),
                ("monthly_limit", models.PositiveIntegerField(default=300)),
                ("price_cents", models.PositiveIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                (
                    "duration_days",
                    models.PositiveBigIntegerField(
                        default=30, help_text="مدت اعتبار اشتراک(روز)"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AIQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField(blank=True, null=True)),
                (
                    "persona",
                    models.CharField(
                        blank=True,
                        help_text="نوع شخصیت یا نقش AI (مثلاً lawyer, educator, career)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "importance",
                    models.PositiveIntegerField(
                        default=1, help_text="وزن یا اهمیت سوال"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AIUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, db_index=True)),
                ("daily_count", models.PositiveIntegerField(default=0)),
                ("monthly_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("starts_at", models.DateTimeField(auto_now_add=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
