# Generated by Django 5.2.5 on 2025-10-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiquestion",
            name="persona",
            field=models.CharField(
                blank=True,
                help_text="نوع شخصیت یا نقش AI (مثلاً lawyer, educator, career)",
                max_length=50,
                null=True,
            ),
        ),
    ]
