# Generated by Django 5.2.5 on 2025-10-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0002_aiquestion_persona"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiquestion",
            name="importance",
            field=models.IntegerField(
                default=1, help_text="وزن یا اهمیت سوال برای memory"
            ),
        ),
    ]
