# Generated by Django 5.2.5 on 2025-10-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0004_aiplan_alter_aiquestion_importance_aierrorlog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiplan",
            name="duration_days",
            field=models.PositiveBigIntegerField(
                default=30, help_text="مدت اعتبار اشتراک(روز)"
            ),
        ),
    ]
