# Generated by Django 5.2.5 on 2025-10-17 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("client_profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="client_profile.clientprofile",
            ),
        ),
    ]
