# Generated by Django 5.2.5 on 2025-10-03 18:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "appointments",
            "0002_remove_appointment_amount_remove_appointment_paid_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="slot",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="slot",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
