# Generated by Django 5.2.5 on 2025-10-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_create_pg_trgm_extension"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="location",
            new_name="location_name",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="cancellation_reason",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="online_link",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="session_type",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="transaction_id",
        ),
        migrations.AddField(
            model_name="appointment",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
