# Generated by Django 5.2.5 on 2025-10-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_slot_created_at_slot_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="slot",
            name="price",
            field=models.DecimalField(decimal_places=0, default=500000, max_digits=10),
        ),
    ]
