# Generated by Django 5.2.5 on 2025-10-19 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_initial"),
        ("client_profile", "0002_initial"),
        ("lawyer_profile", "0003_remove_lawyerprofile_document_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="client",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="lawyer",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="rescheduled_from",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="slot",
        ),
        migrations.AlterUniqueTogether(
            name="slot",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="slot",
            name="lawyer",
        ),
        migrations.CreateModel(
            name="OnlineSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("is_booked", models.BooleanField(default=False)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, default=500000, max_digits=10
                    ),
                ),
                (
                    "lawyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_slots",
                        to="lawyer_profile.lawyerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="OnlineAppointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("google_meet_link", models.URLField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("is_reminder_sent", models.BooleanField(default=False)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_appointments",
                        to="client_profile.clientprofile",
                    ),
                ),
                (
                    "lawyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_appointments",
                        to="lawyer_profile.lawyerprofile",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="appointments.onlineslot",
                    ),
                ),
            ],
            options={
                "ordering": ["slot__start_time"],
            },
        ),
    ]
