# Generated by Django 5.2.5 on 2025-10-19 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "appointments",
            "0004_remove_appointment_client_remove_appointment_lawyer_and_more",
        ),
        ("lawyer_profile", "0003_remove_lawyerprofile_document_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Appointment",
        ),
        migrations.DeleteModel(
            name="Slot",
        ),
        migrations.AlterUniqueTogether(
            name="onlineslot",
            unique_together={("lawyer", "start_time", "end_time")},
        ),
    ]
