# Generated by Django 5.2.5 on 2025-10-20 19:36

import client_profile.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_profile", "0002_initial"),
        ("lawyer_profile", "0003_remove_lawyerprofile_document_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientprofile",
            name="favorites",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorited_by",
                to="lawyer_profile.lawyerprofile",
            ),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="is_phone_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="last_login_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="last_login_user_agent",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="phone_verification_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="phone_verification_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=client_profile.models.client_avatar_path,
            ),
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=512, null=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revoked", models.BooleanField(default=False)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="client_profile.clientprofile",
                    ),
                ),
            ],
        ),
    ]
