# Generated by Django 5.2.5 on 2025-10-23 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client_profile", "0003_clientprofile_favorites_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Device",
        ),
    ]
