# Generated by Django 5.2.5 on 2025-10-02 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={},
        ),
    ]
