# Generated by Django 5.2.5 on 2025-10-02 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notification_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["created_at"]},
        ),
    ]
