# Generated by Django 5.2.5 on 2025-10-19 18:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={},
        ),
        migrations.RemoveField(
            model_name="notification",
            name="link",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="status",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("appointment_confirmed", "Appointment Confirmed"),
                    ("appointment_reminder", "Appointment Reminder"),
                    ("payment_success", "Payment Success"),
                ],
                default="reminder your meeting is at 00:00",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="notification",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
